### PR TITLE
added cuts the legend of Fig. 31

### PR DESCRIPTION
**Pull request by jozzez1**

### CODE REVIEW

**Comment by jozzez1** [comment]
Okay, I fixed the 3rd step of the analysis to produce the legends on the required plots (Fig. 31 and 32).

Cheers,
Joze

**Comment by quertenmont** [comment]
Thanks.... I took the changes, but since I add to resolve a conflict I can't merge this PR

**Comment by jozzez1** [comment]
Okay, I'll resolve the conflict now.

**Comment by quertenmont** [comment]
???

As I said, I already did it and merged it... It's just that I didn't used
your PR

Loic

2015-12-02 13:07 GMT+01:00 Jože Zobec notifications@github.com:

> Okay, I'll resolve the conflict now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/quertenmont/cmssw/pull/22#issuecomment-161272966.

## 

---

Loic Quertenmont - European Organization for Nuclear Research (CERN) - CMS
experiment
Office CERN   : bldg.40, RB-08
Phone CERN    : +41 2276 71548
Mobile BE     : +32 474 831531
WWW           : http://www.fynu.ucl.ac.be/users/l.quertenmont/

**Comment by jozzez1** [comment]
Oh, ok. I didn't understand.

**Pull request closed without merging**
