### PR TITLE
Run2 hscp v9 an edits2

### PR DESCRIPTION
**Pull request by jozzez1**
Still have to find a way to adjust figures 21, 22, 23, 24. But the rest looks much better.

### CODE REVIEW

**Comment by quertenmont** [comment]
ok, I wait for the 4 missing pictures update
it should take only a few minutes

2015-12-03 15:04 GMT+01:00 Jože Zobec notifications@github.com:

> Still have to find a way to adjust figures 21, 22, 23, 24. But the rest
> 
> ## looks much better.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/quertenmont/cmssw/pull/24
> Commit Summary
> - Merged Run2HSCP_v9 from repository quertenmont
> - Merge remote-tracking branch 'cmssw-fromLoic/Run2HSCP_v9' into
>   Run2HSCP_v9
> - Merge remote-tracking branch 'cmssw-fromLoic/Run2HSCP_v9' into
>   Run2HSCP_v9
> - Merge remote-tracking branch 'cmssw-fromLoic/Run2HSCP_v9' into
>   Run2HSCP_v9
> - changed some plots, some still have to be edited
> 
> File Changes
> - _M_ SUSYBSMAnalysis/HSCP/test/AnalysisCode/Analysis_PlotStructure.h
>   https://github.com/quertenmont/cmssw/pull/24/files#diff-0 (22)
> - _M_ SUSYBSMAnalysis/HSCP/test/AnalysisCode/Analysis_Step3_MakePlots.C
>   https://github.com/quertenmont/cmssw/pull/24/files#diff-1 (20)
> 
> Patch Links:
> - https://github.com/quertenmont/cmssw/pull/24.patch
> - https://github.com/quertenmont/cmssw/pull/24.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/quertenmont/cmssw/pull/24.

## 

---

Loic Quertenmont - European Organization for Nuclear Research (CERN) - CMS
experiment
Office CERN   : bldg.40, RB-08
Phone CERN    : +41 2276 71548
Mobile BE     : +32 474 831531
WWW           : http://www.fynu.ucl.ac.be/users/l.quertenmont/

**Comment by jozzez1** [comment]
Okay, I did the changes to those four figures only. I shifted the legend a bit upwards and also I increased the range of the Y axis.

If you want, I can also edit other control plots to use the same parameters.

Cheers,
Joze

**Comment by quertenmont** [comment]
it's ok for now, I guess

Thanks!

2015-12-03 15:29 GMT+01:00 Jože Zobec notifications@github.com:

> Okay, I did the changes to those four figures only. I shifted the legend a
> bit upwards and also I increased the range of the Y axis.
> 
> If you want, I can also edit other control plots to use the same
> parameters.
> 
> Cheers,
> Joze
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/quertenmont/cmssw/pull/24#issuecomment-161655724.

## 

---

Loic Quertenmont - European Organization for Nuclear Research (CERN) - CMS
experiment
Office CERN   : bldg.40, RB-08
Phone CERN    : +41 2276 71548
Mobile BE     : +32 474 831531
WWW           : http://www.fynu.ucl.ac.be/users/l.quertenmont/

**Comment by quertenmont** [comment]
Thanks Joze,

Can you put in green on the twiki the few points that you've done
and also do the changes on Fig35 (it was suggested to use the same scale
for all 3 plots,
I think you can set all the three to yMax = 0.35 or 0.40

Thanks,
Loic

2015-12-03 16:03 GMT+01:00 Loic Quertenmont loic.quertenmont@gmail.com:

> it's ok for now, I guess
> 
> Thanks!
> 
> 2015-12-03 15:29 GMT+01:00 Jože Zobec notifications@github.com:
> 
> > Okay, I did the changes to those four figures only. I shifted the legend
> > a bit upwards and also I increased the range of the Y axis.
> > 
> > If you want, I can also edit other control plots to use the same
> > parameters.
> > 
> > Cheers,
> > Joze
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/quertenmont/cmssw/pull/24#issuecomment-161655724.
> 
> ## 
> 
> ---
> 
> Loic Quertenmont - European Organization for Nuclear Research (CERN) - CMS
> experiment
> Office CERN   : bldg.40, RB-08
> Phone CERN    : +41 2276 71548
> Mobile BE     : +32 474 831531
> WWW           : http://www.fynu.ucl.ac.be/users/l.quertenmont/

## 

---

Loic Quertenmont - European Organization for Nuclear Research (CERN) - CMS
experiment
Office CERN   : bldg.40, RB-08
Phone CERN    : +41 2276 71548
Mobile BE     : +32 474 831531
WWW           : http://www.fynu.ucl.ac.be/users/l.quertenmont/

**Comment by jozzez1** [comment]
Okay, I'll do it.

**Pull request merged**
